theme: jekyll-theme-minimal
lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
name: Setup Yarn
uses: mskelton/setup-yarn@v1.0.1
name: Build and push Docker images
uses: docker/build-push-action@v2.7.0
